# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

# Pods for BernardAV
def import_pods
  pod 'lf', '~> 0.5.0'
end

target 'BernardAV' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '8.0'
  import_pods

  

  target 'BernardAVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BernardAVUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
